### ISSUE TITLE
Adding contributors 

### ISSUE THREAD

**Issue by RasoulNik** [logological/heria#2]
have followed the instructions and created the heria-proposal.tex file. However, when I want to add more than three partners in the heria-proposal.tex file, it leads to many errors.

**Comment by logological** [comment]
I'm afraid you haven't provided enough information to help diagnose the problem.  Could you please give the text of the error message here?

**Comment by RasoulNik** [comment]
Here is the full log file:

[error-3-participants.txt](https://github.com/logological/heria/files/14814983/error-3-participants.txt)

I followed the instructions in the README file for creating the heria-proposal.tex and modified it.

```
\participant
  {Center1} % Participant organization name
  {Ins1} % Participant short name
  {ES} % Country

\participant
  {Center2} % Participant organization name
  {Ins2} % Participant short name
  {ES} % Country

\participant
  {Center3} % Participant organization name
  {Ins3} % Participant short name
  {ES} % Country
```

My guess is that the sample participants are somehow hardcoded, and when I change them or increase their number, it does not compile.

**Comment by logological** [comment]
In your case, the problem seems to be that you changed the short names of the participants but then failed to change anything else in the example proposal.  Every participant you add (or change) needs to have a corresponding `\staffeffort` command for each work package, and all other `\staffeffort` commands, as well as the commands defining each work package, deliverable, and cost, need to reference a previously defined participant by its short name.

**Comment by logological** [comment]
Closing due to lack of response.
